### ISSUE TITLE
[Feature] Add Index alias after documents were added successfully with scout:import

### ISSUE THREAD

**Issue by SineMah** [matchish/laravel-scout-elasticsearch#224] opened 2022-12-08 10:17 UTC
Hey Devs,
i noticed following during an error of creating an index. Elasticsearch/OpenSearch is the searchable view layer of the application. The index was created successfully. The app started to add documents to the new index. It crashed because of some errors. 
(the errors are fixed now. It was a result of strict mapping policy and doesn't matter here)
The app showed some duplicated entries. After a short look i noticed two indices with the same alias. I reproduced the behaviour locally and found the reason:

![Screenshot 2022-12-08 at 10 43 58](https://user-images.githubusercontent.com/8180962/206420916-c462f6ea-5fa5-4af6-81dc-ddabd535b1f6.png)

CreateWriteIndex Line 80 adds an index to the aliases array which will be later added to to config which is passed in the index creation request to Elasticsearch.
Is there a reason to add the index alias in this early stage and show duplicated entries until the scout import process (deleting the old index) is finished?

I would want to change the behaviour to add the alias after the documents were added. Adding Documents can be a time consuming process e.g. with geo objects.

**Comment by matchish** [comment] 2022-12-09 08:47
Hi. We add alias to write index on that stage to be able clean up indices on next import if current import fail.I mean without alias we don't know which index we have to delete.
https://github.com/matchish/laravel-scout-elasticsearch/blob/master/src/Jobs/Stages/CleanUp.php#L40

**Comment by SineMah** [comment] 2022-12-09 14:25
It might be a solution to iterate over all indixes with the pattern `^(\w+)_(\d{10})$`, check if the first group is the alias, sort all with the timestamp and delete all except the latest. This should be fine with the convention if i dont miss anything.

**Comment by matchish** [comment] 2022-12-09 15:34
Another issue that once reindex completed(but before we added an alias to new index) and new update come, it will go to old index and next step we lost it, because old index will be deleted. That's why we mark alias for new index as is_write_index

**Comment by matchish** [comment] 2022-12-09 15:43
@hkulekci Do you have something in mind?

**Comment by SineMah** [comment] 2023-01-10 09:53
PoC of my idea:
https://github.com/matchish/laravel-scout-elasticsearch/commit/4db0f4e6b8fce3f168be3077911d23ad1a729ee4

> Another issue that once reindex completed(but before we added an alias to new index) and new update come, it will go to old index and next step we lost it, because old index will be deleted. That's why we mark alias for new index as is_write_index

This is still an issue. ES/OS is just a view layer for me and recent updated entries are fired with events.

**Comment by hkulekci** [comment] 2023-01-16 18:49
> @hkulekci Do you have something in mind?

Sorry I was too busy these days. I will check this issue next weekend. 👍

**Comment by matchish** [comment] 2023-01-16 18:58
Thank you @hkulekci I thought about collapsing search results https://www.elastic.co/guide/en/elasticsearch/reference/current/collapse-search-results.html but doesn't look like simple solution so looking something else

**Comment by hkulekci** [comment] 2023-01-17 13:25
I think collapsing can be another problem. Collapsing will pick one of the data and the data can be older one. So, the end user will not see recent data. In fact, I could not understand the real problem of this issue. Import is working like below : 

```php
// ImportStages.php
        return (new self([
            new CleanUp($source),
            new CreateWriteIndex($source, $index),
            PullFromSource::chunked($source),
            new RefreshIndex($index),
            new SwitchToNewAndRemoveOldIndex($source, $index),
        ]))->flatten()->filter();
```

So, according to this part, somehow there should not be another index with same aliases, right? So, there should be an error in one of this commands and that index left as idle. Could you give me a list of commands or something to reproduce this issue?

**Comment by hkulekci** [comment] 2023-01-18 15:12
Ahh, I see now. I think I lose my focus these days. Let me think on it from this angle, again.

**Comment by hkulekci** [comment] 2023-01-26 21:45
I could not find a better solution, but I have an idea here to implement a solution. For example, we have an index here as `test_01` for the Model `App\Models\Test`. We want to import the index from scratch again. 

So, when I start the import. The `CleanUp()` will work and clear the indices with `is_write_index: true`. Then `CreateWriteIndex()` will create a write index. After this stage, we will reindex the data into our new index. But during the reindex, we will get the documents duplicate. So, to solve this problem. I suggest using a filter inside the alias, something like this:

```
POST _aliases
{
  "actions": [
    {
      "add": {
        "index": "test_02",
        "alias": "test_alias",
        "is_write_index": true,
        "filter": {
          "bool": {
            "must_not": [
              {
                "term": {
                  "_index": "test_02"
                }
              }
            ]
          }
        }
      }
    }
  ]
}
```

Yes, this is a little bit weird :D I know. But, for our new index, this filter automatically excludes the data from our new index.  We are creating an index for just ingesting data and not searching. But, at the end of the reindex, The stages will continue. And We will reach the `SwitchToNewAndRemoveOldIndex()` stage. And we can remove the filter from the alias, and we can remove the old index too.

In this solution, the problem is, we had data as `id:1, id:2, id:3`. And we start the import. New data came from the database. Before the switching index, this new data will be inside the new index. We could not see the updates before switching the index. 

So, what do you think?

**Comment by hkulekci** [comment] 2023-01-26 22:38
You can check my solution on PR #231

**Comment by SineMah** [comment] 2023-01-26 22:56
Looks good so far. I will test it Wednesday or Thursday next week. These days im a bit busy.
I wasn't aware aliases can have filter arguments too. I just know it from create indices. Your solution seems more elegant. :D

In my opinion seeing new data until indexing is finished leads to less confusion. @matchish what do you think?

**Comment by matchish** [comment] 2023-01-27 10:20
https://github.com/matchish/laravel-scout-elasticsearch/issues/224#issuecomment-1405701990
Yeah I saw similar solution but tried to find something where we can achieve visible updates during reindex as well. Looks strange that this case not covered from the box. But looks like option better then this one we don't have. Thank you for the PR! So let's wait when @SineMah will try it and after the feedback we will merge it

**Comment by hkulekci** [comment] 2023-01-27 11:17
The recent updates while reindexing will be inside the new index. But the end user won't see them before reindexing operation finishes. I tried to cover that part, but this made the solution more complex. I think the client user needs to solve this problem herself with a custom command instead of using the library import command.

**Comment by hkulekci** [comment] 2023-01-27 13:21
So, I will check the tests while waiting for response from @SineMah. FYI.

**Comment by SineMah** [comment] 2023-02-01 11:10
I tested it. Short: It works.

Here is how i tested: I searched for a data set with a special uuid. The filter which was in the alias config prohibited results from the write alias. (Even the querying with index name was filtered by the alias filter strictly, which is fine.)
Works with OpenSeach and ElasticSearch.

![image](https://user-images.githubusercontent.com/8180962/216025301-a87765aa-a98b-4395-94ce-c136e077eb17.png)

**Comment by matchish** [comment] 2023-02-01 11:24
@hkulekci @SineMah merged. Thanks for contributing. Thinking about release version. Looks like it breaking changes so should be 7.0.0 . Thoughts?

**Comment by hkulekci** [comment] 2023-02-01 11:25
Nice to hear this. Yeah, we have a new mechanism for the reindex operation. I think we need to move to 7.0, too.

**Comment by matchish** [comment] 2023-02-01 11:37
@SineMah released

**Closed** 2023-02-01 12:33 UTC
Labels: enhancement
